In [1]:
import pandas as pd
#Query script for MySQL client
import pymysql
con = pymysql.connect(host='titlon.uit.no', 
                    user="williavs@ntnu.no", 
                    password="3UqW1EL5TSvZlGml2rCOA", 
                    database='OSE')  
crsr=con.cursor()
crsr.execute("""
	SELECT  * FROM `OSE`.`equity` 
	WHERE year(`Date`) >= 1980
	ORDER BY `Name`,`Date`
""")
r=crsr.fetchall()
df=pd.DataFrame(list(r), columns=[i[0] for i in crsr.description])
df

,Date,SecurityId,CompanyId,Symbol,ISIN,Name,BestBidPrice,BestAskPrice,Open,High,...,lnDeltaOBX,NOWA_DayLnrate,bills_3month_Lnrate,Sector,IN_OSEBX,Equity,Debt,Earnings,debt_ratio,PE
0,2019-07-12,1304857,12720.0,2020,BMG9156K1018,2020 Bulkers,82.05,83.00,87.20,90.00,...,0.000000,0.000056,0.000056,Industrials,0,NaN,NaN,NaN,NaN,NaN
1,2019-07-15,1304857,12720.0,2020,BMG9156K1018,2020 Bulkers,80.05,81.00,83.00,83.98,...,-0.001063,0.000055,0.000056,Industrials,0,NaN,NaN,NaN,NaN,NaN
2,2019-07-16,1304857,12720.0,2020,BMG9156K1018,2020 Bulkers,80.55,81.00,81.00,81.00,...,-0.009158,0.000055,0.000056,Industrials,0,NaN,NaN,NaN,NaN,NaN
3,2019-07-17,1304857,12720.0,2020,BMG9156K1018,2020 Bulkers,80.40,81.00,81.00,81.00,...,-0.008003,0.000055,0.000056,Industrials,0,NaN,NaN,NaN,NaN,NaN
4,2019-07-18,1304857,12720.0,2020,BMG9156K1018,2020 Bulkers,77.40,80.00,80.01,80.01,...,-0.005844,0.000056,0.000057,Industrials,0,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1643738,2015-11-02,67098,8383.0,ZONC,NO0010373947,Zoncolan,0.40,0.75,0.62,0.66,...,0.005338,0.000033,0.000031,Financials,0,17594000.0,326000.0,-21567000.0,0.018192,-0.455862
1643739,2015-11-17,67098,8383.0,ZONC,NO0010373947,Zoncolan,0.55,0.60,0.55,0.55,...,0.015343,0.000033,0.000030,Financials,0,17594000.0,326000.0,-21567000.0,0.018192,-0.379885
1643740,2015-11-19,67098,8383.0,ZONC,NO0010373947,Zoncolan,0.50,0.60,0.55,0.63,...,0.000703,0.000034,0.000030,Financials,0,17594000.0,326000.0,-21567000.0,0.018192,-0.435141
1643741,2015-11-20,67098,8383.0,ZONC,NO0010373947,Zoncolan,0.42,0.63,0.63,0.63,...,-0.004561,0.000034,0.000028,Financials,0,17594000.0,326000.0,-21567000.0,0.018192,-0.435141
1643742,2015-11-23,67098,8383.0,ZONC,NO0010373947,Zoncolan,0.46,0.62,0.50,0.50,...,-0.002421,0.000033,0.000028,Financials,0,17594000.0,326000.0,-21567000.0,0.018192,-0.310815

In [4]:
df.groupby('Name').count()

,Date,SecurityId,CompanyId,Symbol,ISIN,BestBidPrice,BestAskPrice,Open,High,Low,...,lnDeltaOBX,NOWA_DayLnrate,bills_3month_Lnrate,Sector,IN_OSEBX,Equity,Debt,Earnings,debt_ratio,PE
Name,,,,,,,,,,,,,,,,,,,,,
2020 Bulkers,346,346,346,346,346,346,346,346,346,346,...,346,346,346,346,346,0,0,0,0,0
24Seven Technology Group,808,808,808,808,808,785,795,808,808,808,...,808,808,808,808,808,808,808,808,808,808
5th Planet Games,856,856,856,856,856,856,856,856,856,856,...,856,856,856,856,856,128,128,128,128,128
A-pressen,438,438,438,438,438,431,423,438,438,438,...,438,438,438,438,438,438,423,423,423,423
ABG Sundal Collier Holding,6619,6619,6619,6619,6619,6603,6609,6619,6619,6619,...,5629,6619,6619,6619,6619,5629,5034,5034,5034,4801
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zalaris,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599,...,1599,1599,1599,1599,1599,1599,1599,1599,1599,1599
Zenitel,289,289,289,289,289,281,287,289,289,289,...,289,289,289,289,289,208,0,0,0,0
Zoncolan,253,253,253,253,253,232,221,253,253,253,...,253,253,253,253,253,188,188,188,188,188
iGroup,658,658,658,658,658,658,658,658,658,658,...,658,658,658,658,658,619,619,619,619,619
poLight,504,504,504,504,504,504,504,504,504,504,...,504,504,504,504,504,504,504,504,504,504

In [5]:
df.to_csv('OSEBX_data.csv')

In [6]:
df.to_parquet('OSEBX_data.parquet')

In [10]:
df.columns

Index(['Date', 'SecurityId', 'CompanyId', 'Symbol', 'ISIN', 'Name',
       'BestBidPrice', 'BestAskPrice', 'Open', 'High', 'Low', 'Close',
       'OfficialNumberOfTrades', 'OfficialVolume', 'UnofficialNumberOfTrades',
       'UnofficialVolume', 'VolumeWeightedAveragePrice', 'Price',
       'AdjustedPrice', 'Dividends', 'LDividends', 'CorpAdj', 'DividendAdj',
       'Currency', 'Description', 'CountryCode', 'SumAnnualDividends',
       'NumberOfShares', 'CompanyOwnedShares', 'OutstandingShares', 'Exchange',
       'NOKPerForex', 'mktcap', 'OSEBXmktshare_prevmnth',
       'OSEBXAlpha_prevmnth', 'OSEBXBeta_prevmnth', 'SMB', 'HML', 'LIQ', 'MOM',
       'DividendPriceRatio', 'lnDeltaP', 'lnDeltaOSEBX', 'lnDeltaOBX',
       'NOWA_DayLnrate', 'bills_3month_Lnrate', 'Sector', 'IN_OSEBX', 'Equity',
       'Debt', 'Earnings', 'debt_ratio', 'PE'],
      dtype='object')

In [13]:
df2 = df[['Date', 'Symbol', 'AdjustedPrice']]

In [ ]:
df2

In [2]:
df2['Date'] = pd.to_datetime(df2['Date'])

NameError: name 'pd' is not defined